spring:
  profiles:
    active: dev
  application:
    name: user_center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yupao?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&&serverTimezone=Asia/Shanghai
    username: yupao
    password: 123456
  #session 失效时间 单位分钟
  session:
    timeout: 86400
    store-type: redis
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    #Redis 配置
  redis:
    port: 6379
    host: 127.0.0.1
    database: 1
server:
  port: 5432
  servlet:
    context-path: /api
#    session:
#      cookie:
#        domain: localhost

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    local-cache-scope: statement
  global-config:
    db-config:
      logic-delete-field: isDelete  #全局删除的字段实体
      logic-delete-value: 1  #逻辑已删除
      logic-not-delete-value: 0  #逻辑未删除